server:
  port: '@server.port@'
management:
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
  security:
    flag: false

spring:
  application:
    name: @project.name@
    description: @project.description@
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

magista:
  client:
    adapter:
      url: http://localhost:8022/v2/stat
      networkTimeout: 30000

claimmanagement:
  client:
    adapter:
      url: http://localhost:8022/v1/claimmanagement
      networkTimeout: 30000

filestorage:
  expiration.time:
    download:
      hours: 1
    upload:
      hours: 1
  client:
    adapter:
      url: http://localhost:8022/file_storage
      networkTimeout: 30000

partyManagement:
  url: http://hellgate:8022/v1/processing/partymgmt
  timeout: 5000

keycloak:
  realm: internal
  auth-server-url: http://keycloak:8080/auth/
  resource: common-api
  not-before: 0
  ssl-required: none
  realm-public-key:

auth.enabled: true

feedback:
  fromEmail: no-reply@rbkmoney.com
  toEmails:
    - feedback@rbkmoney.com

info:
  version: '@project.version@'
  stage: dev

http.timeout:
  read: 90
  connect: 30

questionary-aggr-proxy:
  url: http://localhost:8022/v1/questionary/proxy
  networkTimeout: 30000

questionary:
  url: http://localhost:8022/v1/questionary
  networkTimeout: 30000

conversations:
  url: http://localhost:8022/v1/conversations
  networkTimeout: 30000

cabi:
  url: http://localhost:8022/v1/cabi
  networkTimeout: 30000

dominant:
  url: http://localhost:8022/v1/domain/repository_client
  networkTimeout: 30000

analytics:
  url: http://localhost:8022/v1/analytics
  networkTimeout: 30000

dudoser:
  url: http://localhost:8022/v1/dudoser
  networkTimeout: 30000
